version: '3.3'

services:
    jekyll:
        command: jekyll serve --watch --force_polling --verbose
        image: jekyll/jekyll:3.8
        ports:
            - '4000:4000'
        restart: always
        volumes:
            - $PWD:/srv/jekyll
